import { StyleSheet } from "react-native";
import AppColors from "../theme/app_colors";

const buttonStyle = StyleSheet.create({
    headerButton: {
        backgroundColor: AppColors.oxfordBlueShade,
        borderRadius: 100,
        paddingLeft: 26,
        paddingVertical: 16,
        marginHorizontal: 30,
        alignItems: "center",
        display: "flex",
        justifyContent: "center",
    },
    extendedButton: {
        backgroundColor: AppColors.cardinal,
        borderRadius: 20,
        height: 80,
        minWidth: "50%",
        alignItems: "center",
        display: "flex",
        justifyContent: "center",
        marginBottom: 20,
    },
    unitButton: {
        backgroundColor: AppColors.oxfordBlueShade,
        borderRadius: 20,
        height: 80,
        minWidth: "25%",
        alignItems: "center",
        display: "flex",
        justifyContent: "center",
    },
    specialUnitButton: {
        backgroundColor: AppColors.rustyRed,
        borderRadius: 20,
        height: 80,
        minWidth: "25%",
        alignItems: "center",
        display: "flex",
        justifyContent: "center",
    },
    keyButton: {  
        backgroundColor: AppColors.oxfordBlueShade,
        borderRadius: 20,
        height: 80,
        minWidth: "22.9%",
        alignItems: "center",
        display: "flex",
        justifyContent: "center",
        marginBottom: 20,
    },  
    specialKeyButton: {
        backgroundColor: AppColors.cardinal,
        borderRadius: 20,
        height: 80,
        minWidth: "22.9%",
        alignItems: "center",
        display: "flex",
        justifyContent: "center",
        marginBottom: 20,
    },
    inputButton: {
        backgroundColor: AppColors.oxfordBlueShade,
        borderRadius: 20,
        minWidth: "80%",
        maxWidth: "90%",
        height: 80,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    specialInputButton: {
        backgroundColor: AppColors.rustyRed,
        borderRadius: 20,
        minWidth: "80%",
        maxWidth: "90%",
        height: 80,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    inputEntry: {
        position: "absolute",
        right: 30,
        display: "flex",
        flexDirection: "row",
    },
});

export default buttonStyle;